# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06549c79fa9c36888b76fcc456272b8225634cfaf67c2499a35dfec84fae24b5e080019d3fcd525be0d8b3a40246e389f8a81cc61a0bb194e1cd0b165b86fd1e

test:
  secret_key_base: a291bd4ce586a94f49aab74211e69001b29b0faadbfda58c3dc3bd2e6a8321999dd78b777da6ff7ee7f8926ce4b47b42d99ce766159a00bcc170bed223c367ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
