# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 980160e22b15b54b1b8cc4cc1f676b1ad141696aed948a3fde83c82e39d583e271ff71898b347c68f854c01d10f64c7af8793fa7e4f0f82a6155f8d7dfe84c3c

test:
  secret_key_base: 43861725051b5511998be8769a748185c483d493d4588df9b8a4975d996943eb8ed32abaed4c1787b1ca7bd87aaf6274fba4148e400529013b2c9130821293a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
