# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5129bcb97d5f74edb92ed9c6ecb9eb2505383fd7b49eac0ae16a14d97ea54b501e4a9ef8183d4eade2c1c06abcf96988151cb5cb0c03b93dfddb7f06763c9c5

test:
  secret_key_base: c639bcd0b60042768f0fcd7205ef1db2a0623a69d5fa1476bdea8d4850dc032042ad8a978eb265f42c68506ca76e5a3a820417b14f05ba140cbaa9699c223221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
