# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b838211b333741093ea71fe75bca0ce3ebadd5bcf03206831ee0b6485295199c97a24094aebd8ff78ae0e602e14b083cf096596cd78ed726c1e83cbf79501f1e

test:
  secret_key_base: fbee473d22b53b251316b24fa8611da57111ae2ccd20b40e66707dbe93fd051ed341553330bb40d9f8cf197a27b12da4f5d0836b16c925e193334cc90b9fb530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
