# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c59b89b77508a230c32e3c4a18da0432e1526c0c2ed7a0327d5d648638f920ae7bb6f16cd6ac22258b9b68c580bbae7ddbd339b97c41cb92fb5e1b7950bb4b9b

test:
  secret_key_base: 453317c497a562c425a1af1c04428d32215e47dbed0a3315ee012cdd39ce96bf3481917c3f800ed23b2b582ededd1f4a392aa0e59eb8bc7609b3bb8a6c31a708

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
