# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa65aac789fe824b12577036a316522ade632acd1f15ce60f769bd6c8e8070a42e7b33549c6e194c0f3334bb731a8aba34e30da2df8eaf15264c5e0a4958353

test:
  secret_key_base: ce7fc4e5ced96121b6cd064125fd3be30a20e783cab161a84cc5bf3f1230220b8941bf50dd9e9fdfd78cac0f75f17566b0de43dd756b11c584786d937da8386d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
